create table if not exists conversion_events (
  id bigint unsigned not null auto_increment primary key,
  event_name varchar(80) not null,
  event_id varchar(255) not null,
  source varchar(20) not null,
  transaction_id varchar(255) null,
  external_id varchar(255) null,
  event_source_url text null,
  referrer_url text null,
  event_time timestamp not null,
  received_at timestamp not null default current_timestamp,
  value decimal(14, 2) null,
  currency varchar(3) null,
  utm_source varchar(255) null,
  utm_medium varchar(255) null,
  utm_campaign varchar(255) null,
  utm_content varchar(255) null,
  utm_term varchar(255) null,
  fbclid text null,
  fbc varchar(255) null,
  fbp varchar(255) null,
  client_ip_address varchar(255) null,
  user_agent text null,
  provider_status varchar(80) null,
  provider_response_id varchar(255) null,
  provider_error text null,
  meta_status varchar(20) null,
  meta_attempts int not null default 0,
  meta_last_attempt_at timestamp null,
  request_id varchar(255) null,
  payload_hash varchar(128) null,
  created_at timestamp not null default current_timestamp,
  updated_at timestamp not null default current_timestamp,
  unique key conversion_events_event_id_uq (event_id),
  key conversion_events_transaction_id_idx (transaction_id),
  key conversion_events_external_id_idx (external_id, event_name, event_time),
  key conversion_events_meta_retry_idx (meta_status, meta_last_attempt_at)
);

create table if not exists purchases (
  transaction_id varchar(255) not null primary key,
  status varchar(20) not null,
  approved_at timestamp null,
  value decimal(14, 2) null,
  currency varchar(3) null,
  product_id varchar(255) null,
  product_name varchar(500) null,
  external_id varchar(255) null,
  external_id_hash varchar(128) null,
  hotmart_event_id varchar(255) null,
  meta_event_id varchar(255) null,
  meta_events_received tinyint(1) not null default 0,
  meta_error text null,
  last_webhook_at timestamp not null default current_timestamp,
  created_at timestamp not null default current_timestamp,
  updated_at timestamp not null default current_timestamp,
  key purchases_status_idx (status),
  key purchases_external_id_idx (external_id)
);
