create table if not exists public.conversion_events (
  id bigint generated by default as identity primary key,
  event_name text not null,
  event_id text not null unique,
  source text not null check (source in ('browser', 'hotmart', 'meta_capi')),
  transaction_id text,
  external_id text,
  event_source_url text,
  referrer_url text,
  event_time timestamptz not null,
  received_at timestamptz not null default now(),
  value numeric(14, 2),
  currency text check (currency is null or currency ~ '^[A-Z]{3}$'),
  utm_source text,
  utm_medium text,
  utm_campaign text,
  utm_content text,
  utm_term text,
  fbclid text,
  fbc text,
  fbp text,
  client_ip_address text,
  user_agent text,
  provider_status text,
  provider_response_id text,
  provider_error text,
  meta_status text check (meta_status is null or meta_status in ('pending', 'processing', 'accepted', 'failed')),
  meta_attempts integer not null default 0,
  meta_last_attempt_at timestamptz,
  request_id text,
  payload_hash text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists conversion_events_transaction_id_idx
  on public.conversion_events (transaction_id);
create index if not exists conversion_events_external_id_idx
  on public.conversion_events (external_id, event_name, event_time desc);
create index if not exists conversion_events_meta_retry_idx
  on public.conversion_events (meta_status, meta_last_attempt_at);

create table if not exists public.purchases (
  transaction_id text primary key,
  status text not null check (status in ('approved', 'complete', 'refunded', 'chargeback', 'canceled', 'expired')),
  approved_at timestamptz,
  value numeric(14, 2),
  currency text check (currency is null or currency ~ '^[A-Z]{3}$'),
  product_id text,
  product_name text,
  external_id text,
  external_id_hash text,
  hotmart_event_id text,
  meta_event_id text,
  meta_events_received boolean not null default false,
  meta_error text,
  last_webhook_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists purchases_status_idx on public.purchases (status);
create index if not exists purchases_external_id_idx on public.purchases (external_id);

create or replace function public.claim_conversion_event(p_event_id text)
returns table (claimed boolean, current_status text)
language plpgsql
security definer
set search_path = public
as $$
declare
  updated_row public.conversion_events;
begin
  update public.conversion_events
  set
    meta_status = 'processing',
    meta_attempts = meta_attempts + 1,
    meta_last_attempt_at = now(),
    updated_at = now()
  where event_id = p_event_id
    and (
      meta_status is null
      or meta_status = 'pending'
      or meta_status = 'failed'
      or (meta_status = 'processing' and meta_last_attempt_at < now() - interval '2 minutes')
    )
  returning * into updated_row;

  if found then
    return query select true, updated_row.meta_status;
  else
    return query
      select false, ce.meta_status
      from public.conversion_events ce
      where ce.event_id = p_event_id;
  end if;
end;
$$;

revoke all on function public.claim_conversion_event(text) from public, anon, authenticated;
grant execute on function public.claim_conversion_event(text) to service_role;

create or replace function public.touch_conversion_events_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists conversion_events_updated_at on public.conversion_events;
create trigger conversion_events_updated_at
before update on public.conversion_events
for each row execute function public.touch_conversion_events_updated_at();

drop trigger if exists purchases_updated_at on public.purchases;
create trigger purchases_updated_at
before update on public.purchases
for each row execute function public.touch_conversion_events_updated_at();

alter table public.conversion_events enable row level security;
alter table public.purchases enable row level security;

revoke all on public.conversion_events from anon, authenticated;
revoke all on public.purchases from anon, authenticated;
